//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megacasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Casting()
        {
            this.Artiste = new HashSet<Artiste>();
        }
    
        public int Id_Casting { get; set; }
        public string Intitule { get; set; }
        public int Reference { get; set; }
        public System.DateTime Date_debut_publication { get; set; }
        public int Nbr_poste { get; set; }
        public string Localisation { get; set; }
        public string Description_poste { get; set; }
        public string Description_profil { get; set; }
        public string Coordonnees { get; set; }
        public System.DateTime Duree_diffusion { get; set; }
        public int Id_Professionnel { get; set; }
        public int Id_Contrat { get; set; }
        public int Id_Metier { get; set; }
    
        public virtual Type_de_contrat Type_de_contrat { get; set; }
        public virtual Métier Métier { get; set; }
        public virtual Professionnel Professionnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artiste> Artiste { get; set; }
    }
}
