//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megacasting.DBLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegacastingEntities : DbContext
    {
        public MegacastingEntities()
            : base("name=MegacastingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artiste> Artiste { get; set; }
        public virtual DbSet<Casting> Casting { get; set; }
        public virtual DbSet<Civilité> Civilité { get; set; }
        public virtual DbSet<Domaine_de_métier> Domaine_de_métier { get; set; }
        public virtual DbSet<Métier> Métier { get; set; }
        public virtual DbSet<Participer> Participer { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Professionnel> Professionnel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_de_contrat> Type_de_contrat { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
