//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megacasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participer
    {
        public int Id_Casting { get; set; }
        public int Id_Artiste { get; set; }
    }
}
