//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megacasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public int Id_Personne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Ville { get; set; }
        public string Adresse { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int Id_Civilite { get; set; }
    
        public virtual Artiste Artiste { get; set; }
        public virtual Civilité Civilité { get; set; }
        public virtual Professionnel Professionnel { get; set; }
    }
}
